az network route-table route create --resource-group udr-test --name route0111 --route-table-name RT --address-prefix 10.0.0.0/24 --next-hop-type VirtualAppliance --next-hop-ip-address 10.20.0.4
az network route-table route create --resource-group udr-test --name route1111 --route-table-name RT --address-prefix 10.0.1.0/24 --next-hop-type VirtualAppliance --next-hop-ip-address 10.20.0.4
az network route-table route create --resource-group udr-test --name route2111 --route-table-name RT --address-prefix 10.0.2.0/24 --next-hop-type VirtualAppliance --next-hop-ip-address 10.20.0.4
az network route-table route create --resource-group udr-test --name route3111 --route-table-name RT --address-prefix 10.0.3.0/24 --next-hop-type VirtualAppliance --next-hop-ip-address 10.20.0.4
az network route-table route create --resource-group udr-test --name route4111 --route-table-name RT --address-prefix 10.0.4.0/24 --next-hop-type VirtualAppliance --next-hop-ip-address 10.20.0.4
az network route-table route create --resource-group udr-test --name route5111 --route-table-name RT --address-prefix 10.0.5.0/24 --next-hop-type VirtualAppliance --next-hop-ip-address 10.20.0.4
az network route-table route create --resource-group udr-test --name route6111 --route-table-name RT --address-prefix 10.0.6.0/24 --next-hop-type VirtualAppliance --next-hop-ip-address 10.20.0.4
az network route-table route create --resource-group udr-test --name route7111 --route-table-name RT --address-prefix 10.0.7.0/24 --next-hop-type VirtualAppliance --next-hop-ip-address 10.20.0.4
az network route-table route create --resource-group udr-test --name route8111 --route-table-name RT --address-prefix 10.0.8.0/24 --next-hop-type VirtualAppliance --next-hop-ip-address 10.20.0.4
az network route-table route create --resource-group udr-test --name route9111 --route-table-name RT --address-prefix 10.0.9.0/24 --next-hop-type VirtualAppliance --next-hop-ip-address 10.20.0.4
az network route-table route create --resource-group udr-test --name route10111 --route-table-name RT --address-prefix 10.0.10.0/24 --next-hop-type VirtualAppliance --next-hop-ip-address 10.20.0.4
az network route-table route create --resource-group udr-test --name route11111 --route-table-name RT --address-prefix 10.0.11.0/24 --next-hop-type VirtualAppliance --next-hop-ip-address 10.20.0.4
az network route-table route create --resource-group udr-test --name route12111 --route-table-name RT --address-prefix 10.0.12.0/24 --next-hop-type VirtualAppliance --next-hop-ip-address 10.20.0.4
az network route-table route create --resource-group udr-test --name route13111 --route-table-name RT --address-prefix 10.0.13.0/24 --next-hop-type VirtualAppliance --next-hop-ip-address 10.20.0.4
az network route-table route create --resource-group udr-test --name route14111 --route-table-name RT --address-prefix 10.0.14.0/24 --next-hop-type VirtualAppliance --next-hop-ip-address 10.20.0.4
az network route-table route create --resource-group udr-test --name route15111 --route-table-name RT --address-prefix 10.0.15.0/24 --next-hop-type VirtualAppliance --next-hop-ip-address 10.20.0.4
az network route-table route create --resource-group udr-test --name route16111 --route-table-name RT --address-prefix 10.0.16.0/24 --next-hop-type VirtualAppliance --next-hop-ip-address 10.20.0.4
az network route-table route create --resource-group udr-test --name route17111 --route-table-name RT --address-prefix 10.0.17.0/24 --next-hop-type VirtualAppliance --next-hop-ip-address 10.20.0.4
az network route-table route create --resource-group udr-test --name route18111 --route-table-name RT --address-prefix 10.0.18.0/24 --next-hop-type VirtualAppliance --next-hop-ip-address 10.20.0.4
az network route-table route create --resource-group udr-test --name route19111 --route-table-name RT --address-prefix 10.0.19.0/24 --next-hop-type VirtualAppliance --next-hop-ip-address 10.20.0.4
az network route-table route create --resource-group udr-test --name route20111 --route-table-name RT --address-prefix 10.0.20.0/24 --next-hop-type VirtualAppliance --next-hop-ip-address 10.20.0.4
az network route-table route create --resource-group udr-test --name route21111 --route-table-name RT --address-prefix 10.0.21.0/24 --next-hop-type VirtualAppliance --next-hop-ip-address 10.20.0.4
az network route-table route create --resource-group udr-test --name route22111 --route-table-name RT --address-prefix 10.0.22.0/24 --next-hop-type VirtualAppliance --next-hop-ip-address 10.20.0.4
az network route-table route create --resource-group udr-test --name route23111 --route-table-name RT --address-prefix 10.0.23.0/24 --next-hop-type VirtualAppliance --next-hop-ip-address 10.20.0.4
az network route-table route create --resource-group udr-test --name route24111 --route-table-name RT --address-prefix 10.0.24.0/24 --next-hop-type VirtualAppliance --next-hop-ip-address 10.20.0.4
az network route-table route create --resource-group udr-test --name route25111 --route-table-name RT --address-prefix 10.0.25.0/24 --next-hop-type VirtualAppliance --next-hop-ip-address 10.20.0.4
az network route-table route create --resource-group udr-test --name route26111 --route-table-name RT --address-prefix 10.0.26.0/24 --next-hop-type VirtualAppliance --next-hop-ip-address 10.20.0.4
az network route-table route create --resource-group udr-test --name route27111 --route-table-name RT --address-prefix 10.0.27.0/24 --next-hop-type VirtualAppliance --next-hop-ip-address 10.20.0.4
az network route-table route create --resource-group udr-test --name route28111 --route-table-name RT --address-prefix 10.0.28.0/24 --next-hop-type VirtualAppliance --next-hop-ip-address 10.20.0.4
az network route-table route create --resource-group udr-test --name route29111 --route-table-name RT --address-prefix 10.0.29.0/24 --next-hop-type VirtualAppliance --next-hop-ip-address 10.20.0.4
az network route-table route create --resource-group udr-test --name route30111 --route-table-name RT --address-prefix 10.0.30.0/24 --next-hop-type VirtualAppliance --next-hop-ip-address 10.20.0.4
az network route-table route create --resource-group udr-test --name route31111 --route-table-name RT --address-prefix 10.0.31.0/24 --next-hop-type VirtualAppliance --next-hop-ip-address 10.20.0.4
az network route-table route create --resource-group udr-test --name route32111 --route-table-name RT --address-prefix 10.0.32.0/24 --next-hop-type VirtualAppliance --next-hop-ip-address 10.20.0.4
az network route-table route create --resource-group udr-test --name route33111 --route-table-name RT --address-prefix 10.0.33.0/24 --next-hop-type VirtualAppliance --next-hop-ip-address 10.20.0.4
az network route-table route create --resource-group udr-test --name route34111 --route-table-name RT --address-prefix 10.0.34.0/24 --next-hop-type VirtualAppliance --next-hop-ip-address 10.20.0.4
az network route-table route create --resource-group udr-test --name route35111 --route-table-name RT --address-prefix 10.0.35.0/24 --next-hop-type VirtualAppliance --next-hop-ip-address 10.20.0.4
az network route-table route create --resource-group udr-test --name route36111 --route-table-name RT --address-prefix 10.0.36.0/24 --next-hop-type VirtualAppliance --next-hop-ip-address 10.20.0.4
az network route-table route create --resource-group udr-test --name route37111 --route-table-name RT --address-prefix 10.0.37.0/24 --next-hop-type VirtualAppliance --next-hop-ip-address 10.20.0.4
az network route-table route create --resource-group udr-test --name route38111 --route-table-name RT --address-prefix 10.0.38.0/24 --next-hop-type VirtualAppliance --next-hop-ip-address 10.20.0.4
az network route-table route create --resource-group udr-test --name route39111 --route-table-name RT --address-prefix 10.0.39.0/24 --next-hop-type VirtualAppliance --next-hop-ip-address 10.20.0.4
az network route-table route create --resource-group udr-test --name route40111 --route-table-name RT --address-prefix 10.0.40.0/24 --next-hop-type VirtualAppliance --next-hop-ip-address 10.20.0.4
az network route-table route create --resource-group udr-test --name route41111 --route-table-name RT --address-prefix 10.0.41.0/24 --next-hop-type VirtualAppliance --next-hop-ip-address 10.20.0.4
az network route-table route create --resource-group udr-test --name route42111 --route-table-name RT --address-prefix 10.0.42.0/24 --next-hop-type VirtualAppliance --next-hop-ip-address 10.20.0.4
az network route-table route create --resource-group udr-test --name route43111 --route-table-name RT --address-prefix 10.0.43.0/24 --next-hop-type VirtualAppliance --next-hop-ip-address 10.20.0.4
az network route-table route create --resource-group udr-test --name route44111 --route-table-name RT --address-prefix 10.0.44.0/24 --next-hop-type VirtualAppliance --next-hop-ip-address 10.20.0.4
az network route-table route create --resource-group udr-test --name route45111 --route-table-name RT --address-prefix 10.0.45.0/24 --next-hop-type VirtualAppliance --next-hop-ip-address 10.20.0.4
az network route-table route create --resource-group udr-test --name route46111 --route-table-name RT --address-prefix 10.0.46.0/24 --next-hop-type VirtualAppliance --next-hop-ip-address 10.20.0.4
az network route-table route create --resource-group udr-test --name route47111 --route-table-name RT --address-prefix 10.0.47.0/24 --next-hop-type VirtualAppliance --next-hop-ip-address 10.20.0.4
az network route-table route create --resource-group udr-test --name route48111 --route-table-name RT --address-prefix 10.0.48.0/24 --next-hop-type VirtualAppliance --next-hop-ip-address 10.20.0.4
az network route-table route create --resource-group udr-test --name route49111 --route-table-name RT --address-prefix 10.0.49.0/24 --next-hop-type VirtualAppliance --next-hop-ip-address 10.20.0.4
az network route-table route create --resource-group udr-test --name route50111 --route-table-name RT --address-prefix 10.0.50.0/24 --next-hop-type VirtualAppliance --next-hop-ip-address 10.20.0.4
az network route-table route create --resource-group udr-test --name route51111 --route-table-name RT --address-prefix 10.0.51.0/24 --next-hop-type VirtualAppliance --next-hop-ip-address 10.20.0.4
az network route-table route create --resource-group udr-test --name route52111 --route-table-name RT --address-prefix 10.0.52.0/24 --next-hop-type VirtualAppliance --next-hop-ip-address 10.20.0.4
az network route-table route create --resource-group udr-test --name route53111 --route-table-name RT --address-prefix 10.0.53.0/24 --next-hop-type VirtualAppliance --next-hop-ip-address 10.20.0.4
az network route-table route create --resource-group udr-test --name route54111 --route-table-name RT --address-prefix 10.0.54.0/24 --next-hop-type VirtualAppliance --next-hop-ip-address 10.20.0.4
az network route-table route create --resource-group udr-test --name route55111 --route-table-name RT --address-prefix 10.0.55.0/24 --next-hop-type VirtualAppliance --next-hop-ip-address 10.20.0.4
az network route-table route create --resource-group udr-test --name route56111 --route-table-name RT --address-prefix 10.0.56.0/24 --next-hop-type VirtualAppliance --next-hop-ip-address 10.20.0.4
az network route-table route create --resource-group udr-test --name route57111 --route-table-name RT --address-prefix 10.0.57.0/24 --next-hop-type VirtualAppliance --next-hop-ip-address 10.20.0.4
az network route-table route create --resource-group udr-test --name route58111 --route-table-name RT --address-prefix 10.0.58.0/24 --next-hop-type VirtualAppliance --next-hop-ip-address 10.20.0.4
az network route-table route create --resource-group udr-test --name route59111 --route-table-name RT --address-prefix 10.0.59.0/24 --next-hop-type VirtualAppliance --next-hop-ip-address 10.20.0.4
az network route-table route create --resource-group udr-test --name route60111 --route-table-name RT --address-prefix 10.0.60.0/24 --next-hop-type VirtualAppliance --next-hop-ip-address 10.20.0.4
az network route-table route create --resource-group udr-test --name route61111 --route-table-name RT --address-prefix 10.0.61.0/24 --next-hop-type VirtualAppliance --next-hop-ip-address 10.20.0.4
az network route-table route create --resource-group udr-test --name route62111 --route-table-name RT --address-prefix 10.0.62.0/24 --next-hop-type VirtualAppliance --next-hop-ip-address 10.20.0.4
az network route-table route create --resource-group udr-test --name route63111 --route-table-name RT --address-prefix 10.0.63.0/24 --next-hop-type VirtualAppliance --next-hop-ip-address 10.20.0.4
az network route-table route create --resource-group udr-test --name route64111 --route-table-name RT --address-prefix 10.0.64.0/24 --next-hop-type VirtualAppliance --next-hop-ip-address 10.20.0.4
az network route-table route create --resource-group udr-test --name route65111 --route-table-name RT --address-prefix 10.0.65.0/24 --next-hop-type VirtualAppliance --next-hop-ip-address 10.20.0.4
az network route-table route create --resource-group udr-test --name route66111 --route-table-name RT --address-prefix 10.0.66.0/24 --next-hop-type VirtualAppliance --next-hop-ip-address 10.20.0.4
az network route-table route create --resource-group udr-test --name route67111 --route-table-name RT --address-prefix 10.0.67.0/24 --next-hop-type VirtualAppliance --next-hop-ip-address 10.20.0.4
az network route-table route create --resource-group udr-test --name route68111 --route-table-name RT --address-prefix 10.0.68.0/24 --next-hop-type VirtualAppliance --next-hop-ip-address 10.20.0.4
az network route-table route create --resource-group udr-test --name route69111 --route-table-name RT --address-prefix 10.0.69.0/24 --next-hop-type VirtualAppliance --next-hop-ip-address 10.20.0.4
az network route-table route create --resource-group udr-test --name route70111 --route-table-name RT --address-prefix 10.0.70.0/24 --next-hop-type VirtualAppliance --next-hop-ip-address 10.20.0.4
az network route-table route create --resource-group udr-test --name route71111 --route-table-name RT --address-prefix 10.0.71.0/24 --next-hop-type VirtualAppliance --next-hop-ip-address 10.20.0.4
az network route-table route create --resource-group udr-test --name route72111 --route-table-name RT --address-prefix 10.0.72.0/24 --next-hop-type VirtualAppliance --next-hop-ip-address 10.20.0.4
az network route-table route create --resource-group udr-test --name route73111 --route-table-name RT --address-prefix 10.0.73.0/24 --next-hop-type VirtualAppliance --next-hop-ip-address 10.20.0.4
az network route-table route create --resource-group udr-test --name route74111 --route-table-name RT --address-prefix 10.0.74.0/24 --next-hop-type VirtualAppliance --next-hop-ip-address 10.20.0.4
az network route-table route create --resource-group udr-test --name route75111 --route-table-name RT --address-prefix 10.0.75.0/24 --next-hop-type VirtualAppliance --next-hop-ip-address 10.20.0.4
az network route-table route create --resource-group udr-test --name route76111 --route-table-name RT --address-prefix 10.0.76.0/24 --next-hop-type VirtualAppliance --next-hop-ip-address 10.20.0.4
az network route-table route create --resource-group udr-test --name route77111 --route-table-name RT --address-prefix 10.0.77.0/24 --next-hop-type VirtualAppliance --next-hop-ip-address 10.20.0.4
az network route-table route create --resource-group udr-test --name route78111 --route-table-name RT --address-prefix 10.0.78.0/24 --next-hop-type VirtualAppliance --next-hop-ip-address 10.20.0.4
az network route-table route create --resource-group udr-test --name route79111 --route-table-name RT --address-prefix 10.0.79.0/24 --next-hop-type VirtualAppliance --next-hop-ip-address 10.20.0.4
az network route-table route create --resource-group udr-test --name route80111 --route-table-name RT --address-prefix 10.0.80.0/24 --next-hop-type VirtualAppliance --next-hop-ip-address 10.20.0.4
az network route-table route create --resource-group udr-test --name route81111 --route-table-name RT --address-prefix 10.0.81.0/24 --next-hop-type VirtualAppliance --next-hop-ip-address 10.20.0.4
az network route-table route create --resource-group udr-test --name route82111 --route-table-name RT --address-prefix 10.0.82.0/24 --next-hop-type VirtualAppliance --next-hop-ip-address 10.20.0.4
az network route-table route create --resource-group udr-test --name route83111 --route-table-name RT --address-prefix 10.0.83.0/24 --next-hop-type VirtualAppliance --next-hop-ip-address 10.20.0.4
az network route-table route create --resource-group udr-test --name route84111 --route-table-name RT --address-prefix 10.0.84.0/24 --next-hop-type VirtualAppliance --next-hop-ip-address 10.20.0.4
az network route-table route create --resource-group udr-test --name route85111 --route-table-name RT --address-prefix 10.0.85.0/24 --next-hop-type VirtualAppliance --next-hop-ip-address 10.20.0.4
az network route-table route create --resource-group udr-test --name route86111 --route-table-name RT --address-prefix 10.0.86.0/24 --next-hop-type VirtualAppliance --next-hop-ip-address 10.20.0.4
az network route-table route create --resource-group udr-test --name route87111 --route-table-name RT --address-prefix 10.0.87.0/24 --next-hop-type VirtualAppliance --next-hop-ip-address 10.20.0.4
az network route-table route create --resource-group udr-test --name route88111 --route-table-name RT --address-prefix 10.0.88.0/24 --next-hop-type VirtualAppliance --next-hop-ip-address 10.20.0.4
az network route-table route create --resource-group udr-test --name route89111 --route-table-name RT --address-prefix 10.0.89.0/24 --next-hop-type VirtualAppliance --next-hop-ip-address 10.20.0.4
az network route-table route create --resource-group udr-test --name route90111 --route-table-name RT --address-prefix 10.0.90.0/24 --next-hop-type VirtualAppliance --next-hop-ip-address 10.20.0.4
az network route-table route create --resource-group udr-test --name route91111 --route-table-name RT --address-prefix 10.0.91.0/24 --next-hop-type VirtualAppliance --next-hop-ip-address 10.20.0.4
az network route-table route create --resource-group udr-test --name route92111 --route-table-name RT --address-prefix 10.0.92.0/24 --next-hop-type VirtualAppliance --next-hop-ip-address 10.20.0.4
az network route-table route create --resource-group udr-test --name route93111 --route-table-name RT --address-prefix 10.0.93.0/24 --next-hop-type VirtualAppliance --next-hop-ip-address 10.20.0.4
az network route-table route create --resource-group udr-test --name route94111 --route-table-name RT --address-prefix 10.0.94.0/24 --next-hop-type VirtualAppliance --next-hop-ip-address 10.20.0.4
az network route-table route create --resource-group udr-test --name route95111 --route-table-name RT --address-prefix 10.0.95.0/24 --next-hop-type VirtualAppliance --next-hop-ip-address 10.20.0.4
az network route-table route create --resource-group udr-test --name route96111 --route-table-name RT --address-prefix 10.0.96.0/24 --next-hop-type VirtualAppliance --next-hop-ip-address 10.20.0.4
az network route-table route create --resource-group udr-test --name route97111 --route-table-name RT --address-prefix 10.0.97.0/24 --next-hop-type VirtualAppliance --next-hop-ip-address 10.20.0.4
az network route-table route create --resource-group udr-test --name route98111 --route-table-name RT --address-prefix 10.0.98.0/24 --next-hop-type VirtualAppliance --next-hop-ip-address 10.20.0.4
az network route-table route create --resource-group udr-test --name route99111 --route-table-name RT --address-prefix 10.0.99.0/24 --next-hop-type VirtualAppliance --next-hop-ip-address 10.20.0.4
az network route-table route create --resource-group udr-test --name route100111 --route-table-name RT --address-prefix 10.0.100.0/24 --next-hop-type VirtualAppliance --next-hop-ip-address 10.20.0.4
