az group create --name udr-test --location westus2
az network vnet create --resource-group udr-test --name VNET --location westus2 --address-prefixes 10.10.0.0/24 --subnet-name test --subnet-prefix 10.10.0.0/26
az network route-table create --name RT --resource-group udr-test --location westus2
az network route-table route create --resource-group udr-test --name route0 --route-table-name RT --address-prefix 10.0.0.0/24 --next-hop-type VirtualAppliance --next-hop-ip-address 10.20.0.4
az network route-table route create --resource-group udr-test --name route1 --route-table-name RT --address-prefix 10.0.1.0/24 --next-hop-type VirtualAppliance --next-hop-ip-address 10.20.0.4
az network route-table route create --resource-group udr-test --name route2 --route-table-name RT --address-prefix 10.0.2.0/24 --next-hop-type VirtualAppliance --next-hop-ip-address 10.20.0.4
az network route-table route create --resource-group udr-test --name route3 --route-table-name RT --address-prefix 10.0.3.0/24 --next-hop-type VirtualAppliance --next-hop-ip-address 10.20.0.4
az network route-table route create --resource-group udr-test --name route4 --route-table-name RT --address-prefix 10.0.4.0/24 --next-hop-type VirtualAppliance --next-hop-ip-address 10.20.0.4
az network route-table route create --resource-group udr-test --name route5 --route-table-name RT --address-prefix 10.0.5.0/24 --next-hop-type VirtualAppliance --next-hop-ip-address 10.20.0.4
az network route-table route create --resource-group udr-test --name route6 --route-table-name RT --address-prefix 10.0.6.0/24 --next-hop-type VirtualAppliance --next-hop-ip-address 10.20.0.4
az network route-table route create --resource-group udr-test --name route7 --route-table-name RT --address-prefix 10.0.7.0/24 --next-hop-type VirtualAppliance --next-hop-ip-address 10.20.0.4
az network route-table route create --resource-group udr-test --name route8 --route-table-name RT --address-prefix 10.0.8.0/24 --next-hop-type VirtualAppliance --next-hop-ip-address 10.20.0.4
az network route-table route create --resource-group udr-test --name route9 --route-table-name RT --address-prefix 10.0.9.0/24 --next-hop-type VirtualAppliance --next-hop-ip-address 10.20.0.4
az network route-table route create --resource-group udr-test --name route10 --route-table-name RT --address-prefix 10.0.10.0/24 --next-hop-type VirtualAppliance --next-hop-ip-address 10.20.0.4
az network route-table route create --resource-group udr-test --name route11 --route-table-name RT --address-prefix 10.0.11.0/24 --next-hop-type VirtualAppliance --next-hop-ip-address 10.20.0.4
az network route-table route create --resource-group udr-test --name route12 --route-table-name RT --address-prefix 10.0.12.0/24 --next-hop-type VirtualAppliance --next-hop-ip-address 10.20.0.4
az network route-table route create --resource-group udr-test --name route13 --route-table-name RT --address-prefix 10.0.13.0/24 --next-hop-type VirtualAppliance --next-hop-ip-address 10.20.0.4
az network route-table route create --resource-group udr-test --name route14 --route-table-name RT --address-prefix 10.0.14.0/24 --next-hop-type VirtualAppliance --next-hop-ip-address 10.20.0.4
az network route-table route create --resource-group udr-test --name route15 --route-table-name RT --address-prefix 10.0.15.0/24 --next-hop-type VirtualAppliance --next-hop-ip-address 10.20.0.4
az network route-table route create --resource-group udr-test --name route16 --route-table-name RT --address-prefix 10.0.16.0/24 --next-hop-type VirtualAppliance --next-hop-ip-address 10.20.0.4
az network route-table route create --resource-group udr-test --name route17 --route-table-name RT --address-prefix 10.0.17.0/24 --next-hop-type VirtualAppliance --next-hop-ip-address 10.20.0.4
az network route-table route create --resource-group udr-test --name route18 --route-table-name RT --address-prefix 10.0.18.0/24 --next-hop-type VirtualAppliance --next-hop-ip-address 10.20.0.4
az network route-table route create --resource-group udr-test --name route19 --route-table-name RT --address-prefix 10.0.19.0/24 --next-hop-type VirtualAppliance --next-hop-ip-address 10.20.0.4
az network route-table route create --resource-group udr-test --name route20 --route-table-name RT --address-prefix 10.0.20.0/24 --next-hop-type VirtualAppliance --next-hop-ip-address 10.20.0.4
az network route-table route create --resource-group udr-test --name route21 --route-table-name RT --address-prefix 10.0.21.0/24 --next-hop-type VirtualAppliance --next-hop-ip-address 10.20.0.4
az network route-table route create --resource-group udr-test --name route22 --route-table-name RT --address-prefix 10.0.22.0/24 --next-hop-type VirtualAppliance --next-hop-ip-address 10.20.0.4
az network route-table route create --resource-group udr-test --name route23 --route-table-name RT --address-prefix 10.0.23.0/24 --next-hop-type VirtualAppliance --next-hop-ip-address 10.20.0.4
az network route-table route create --resource-group udr-test --name route24 --route-table-name RT --address-prefix 10.0.24.0/24 --next-hop-type VirtualAppliance --next-hop-ip-address 10.20.0.4
az network route-table route create --resource-group udr-test --name route25 --route-table-name RT --address-prefix 10.0.25.0/24 --next-hop-type VirtualAppliance --next-hop-ip-address 10.20.0.4
az network route-table route create --resource-group udr-test --name route26 --route-table-name RT --address-prefix 10.0.26.0/24 --next-hop-type VirtualAppliance --next-hop-ip-address 10.20.0.4
az network route-table route create --resource-group udr-test --name route27 --route-table-name RT --address-prefix 10.0.27.0/24 --next-hop-type VirtualAppliance --next-hop-ip-address 10.20.0.4
az network route-table route create --resource-group udr-test --name route28 --route-table-name RT --address-prefix 10.0.28.0/24 --next-hop-type VirtualAppliance --next-hop-ip-address 10.20.0.4
az network route-table route create --resource-group udr-test --name route29 --route-table-name RT --address-prefix 10.0.29.0/24 --next-hop-type VirtualAppliance --next-hop-ip-address 10.20.0.4
az network route-table route create --resource-group udr-test --name route30 --route-table-name RT --address-prefix 10.0.30.0/24 --next-hop-type VirtualAppliance --next-hop-ip-address 10.20.0.4
az network route-table route create --resource-group udr-test --name route31 --route-table-name RT --address-prefix 10.0.31.0/24 --next-hop-type VirtualAppliance --next-hop-ip-address 10.20.0.4
az network route-table route create --resource-group udr-test --name route32 --route-table-name RT --address-prefix 10.0.32.0/24 --next-hop-type VirtualAppliance --next-hop-ip-address 10.20.0.4
az network route-table route create --resource-group udr-test --name route33 --route-table-name RT --address-prefix 10.0.33.0/24 --next-hop-type VirtualAppliance --next-hop-ip-address 10.20.0.4
az network route-table route create --resource-group udr-test --name route34 --route-table-name RT --address-prefix 10.0.34.0/24 --next-hop-type VirtualAppliance --next-hop-ip-address 10.20.0.4
az network route-table route create --resource-group udr-test --name route35 --route-table-name RT --address-prefix 10.0.35.0/24 --next-hop-type VirtualAppliance --next-hop-ip-address 10.20.0.4
az network route-table route create --resource-group udr-test --name route36 --route-table-name RT --address-prefix 10.0.36.0/24 --next-hop-type VirtualAppliance --next-hop-ip-address 10.20.0.4
az network route-table route create --resource-group udr-test --name route37 --route-table-name RT --address-prefix 10.0.37.0/24 --next-hop-type VirtualAppliance --next-hop-ip-address 10.20.0.4
az network route-table route create --resource-group udr-test --name route38 --route-table-name RT --address-prefix 10.0.38.0/24 --next-hop-type VirtualAppliance --next-hop-ip-address 10.20.0.4
az network route-table route create --resource-group udr-test --name route39 --route-table-name RT --address-prefix 10.0.39.0/24 --next-hop-type VirtualAppliance --next-hop-ip-address 10.20.0.4
az network route-table route create --resource-group udr-test --name route40 --route-table-name RT --address-prefix 10.0.40.0/24 --next-hop-type VirtualAppliance --next-hop-ip-address 10.20.0.4
az network route-table route create --resource-group udr-test --name route41 --route-table-name RT --address-prefix 10.0.41.0/24 --next-hop-type VirtualAppliance --next-hop-ip-address 10.20.0.4
az network route-table route create --resource-group udr-test --name route42 --route-table-name RT --address-prefix 10.0.42.0/24 --next-hop-type VirtualAppliance --next-hop-ip-address 10.20.0.4
az network route-table route create --resource-group udr-test --name route43 --route-table-name RT --address-prefix 10.0.43.0/24 --next-hop-type VirtualAppliance --next-hop-ip-address 10.20.0.4
az network route-table route create --resource-group udr-test --name route44 --route-table-name RT --address-prefix 10.0.44.0/24 --next-hop-type VirtualAppliance --next-hop-ip-address 10.20.0.4
az network route-table route create --resource-group udr-test --name route45 --route-table-name RT --address-prefix 10.0.45.0/24 --next-hop-type VirtualAppliance --next-hop-ip-address 10.20.0.4
az network route-table route create --resource-group udr-test --name route46 --route-table-name RT --address-prefix 10.0.46.0/24 --next-hop-type VirtualAppliance --next-hop-ip-address 10.20.0.4
az network route-table route create --resource-group udr-test --name route47 --route-table-name RT --address-prefix 10.0.47.0/24 --next-hop-type VirtualAppliance --next-hop-ip-address 10.20.0.4
az network route-table route create --resource-group udr-test --name route48 --route-table-name RT --address-prefix 10.0.48.0/24 --next-hop-type VirtualAppliance --next-hop-ip-address 10.20.0.4
az network route-table route create --resource-group udr-test --name route49 --route-table-name RT --address-prefix 10.0.49.0/24 --next-hop-type VirtualAppliance --next-hop-ip-address 10.20.0.4
az network route-table route create --resource-group udr-test --name route50 --route-table-name RT --address-prefix 10.0.50.0/24 --next-hop-type VirtualAppliance --next-hop-ip-address 10.20.0.4
az network route-table route create --resource-group udr-test --name route51 --route-table-name RT --address-prefix 10.0.51.0/24 --next-hop-type VirtualAppliance --next-hop-ip-address 10.20.0.4
az network route-table route create --resource-group udr-test --name route52 --route-table-name RT --address-prefix 10.0.52.0/24 --next-hop-type VirtualAppliance --next-hop-ip-address 10.20.0.4
az network route-table route create --resource-group udr-test --name route53 --route-table-name RT --address-prefix 10.0.53.0/24 --next-hop-type VirtualAppliance --next-hop-ip-address 10.20.0.4
az network route-table route create --resource-group udr-test --name route54 --route-table-name RT --address-prefix 10.0.54.0/24 --next-hop-type VirtualAppliance --next-hop-ip-address 10.20.0.4
az network route-table route create --resource-group udr-test --name route55 --route-table-name RT --address-prefix 10.0.55.0/24 --next-hop-type VirtualAppliance --next-hop-ip-address 10.20.0.4
az network route-table route create --resource-group udr-test --name route56 --route-table-name RT --address-prefix 10.0.56.0/24 --next-hop-type VirtualAppliance --next-hop-ip-address 10.20.0.4
az network route-table route create --resource-group udr-test --name route57 --route-table-name RT --address-prefix 10.0.57.0/24 --next-hop-type VirtualAppliance --next-hop-ip-address 10.20.0.4
az network route-table route create --resource-group udr-test --name route58 --route-table-name RT --address-prefix 10.0.58.0/24 --next-hop-type VirtualAppliance --next-hop-ip-address 10.20.0.4
az network route-table route create --resource-group udr-test --name route59 --route-table-name RT --address-prefix 10.0.59.0/24 --next-hop-type VirtualAppliance --next-hop-ip-address 10.20.0.4
az network route-table route create --resource-group udr-test --name route60 --route-table-name RT --address-prefix 10.0.60.0/24 --next-hop-type VirtualAppliance --next-hop-ip-address 10.20.0.4
az network route-table route create --resource-group udr-test --name route61 --route-table-name RT --address-prefix 10.0.61.0/24 --next-hop-type VirtualAppliance --next-hop-ip-address 10.20.0.4
az network route-table route create --resource-group udr-test --name route62 --route-table-name RT --address-prefix 10.0.62.0/24 --next-hop-type VirtualAppliance --next-hop-ip-address 10.20.0.4
az network route-table route create --resource-group udr-test --name route63 --route-table-name RT --address-prefix 10.0.63.0/24 --next-hop-type VirtualAppliance --next-hop-ip-address 10.20.0.4
az network route-table route create --resource-group udr-test --name route64 --route-table-name RT --address-prefix 10.0.64.0/24 --next-hop-type VirtualAppliance --next-hop-ip-address 10.20.0.4
az network route-table route create --resource-group udr-test --name route65 --route-table-name RT --address-prefix 10.0.65.0/24 --next-hop-type VirtualAppliance --next-hop-ip-address 10.20.0.4
az network route-table route create --resource-group udr-test --name route66 --route-table-name RT --address-prefix 10.0.66.0/24 --next-hop-type VirtualAppliance --next-hop-ip-address 10.20.0.4
az network route-table route create --resource-group udr-test --name route67 --route-table-name RT --address-prefix 10.0.67.0/24 --next-hop-type VirtualAppliance --next-hop-ip-address 10.20.0.4
az network route-table route create --resource-group udr-test --name route68 --route-table-name RT --address-prefix 10.0.68.0/24 --next-hop-type VirtualAppliance --next-hop-ip-address 10.20.0.4
az network route-table route create --resource-group udr-test --name route69 --route-table-name RT --address-prefix 10.0.69.0/24 --next-hop-type VirtualAppliance --next-hop-ip-address 10.20.0.4
az network route-table route create --resource-group udr-test --name route70 --route-table-name RT --address-prefix 10.0.70.0/24 --next-hop-type VirtualAppliance --next-hop-ip-address 10.20.0.4
az network route-table route create --resource-group udr-test --name route71 --route-table-name RT --address-prefix 10.0.71.0/24 --next-hop-type VirtualAppliance --next-hop-ip-address 10.20.0.4
az network route-table route create --resource-group udr-test --name route72 --route-table-name RT --address-prefix 10.0.72.0/24 --next-hop-type VirtualAppliance --next-hop-ip-address 10.20.0.4
az network route-table route create --resource-group udr-test --name route73 --route-table-name RT --address-prefix 10.0.73.0/24 --next-hop-type VirtualAppliance --next-hop-ip-address 10.20.0.4
az network route-table route create --resource-group udr-test --name route74 --route-table-name RT --address-prefix 10.0.74.0/24 --next-hop-type VirtualAppliance --next-hop-ip-address 10.20.0.4
az network route-table route create --resource-group udr-test --name route75 --route-table-name RT --address-prefix 10.0.75.0/24 --next-hop-type VirtualAppliance --next-hop-ip-address 10.20.0.4
az network route-table route create --resource-group udr-test --name route76 --route-table-name RT --address-prefix 10.0.76.0/24 --next-hop-type VirtualAppliance --next-hop-ip-address 10.20.0.4
az network route-table route create --resource-group udr-test --name route77 --route-table-name RT --address-prefix 10.0.77.0/24 --next-hop-type VirtualAppliance --next-hop-ip-address 10.20.0.4
az network route-table route create --resource-group udr-test --name route78 --route-table-name RT --address-prefix 10.0.78.0/24 --next-hop-type VirtualAppliance --next-hop-ip-address 10.20.0.4
az network route-table route create --resource-group udr-test --name route79 --route-table-name RT --address-prefix 10.0.79.0/24 --next-hop-type VirtualAppliance --next-hop-ip-address 10.20.0.4
az network route-table route create --resource-group udr-test --name route80 --route-table-name RT --address-prefix 10.0.80.0/24 --next-hop-type VirtualAppliance --next-hop-ip-address 10.20.0.4
az network route-table route create --resource-group udr-test --name route81 --route-table-name RT --address-prefix 10.0.81.0/24 --next-hop-type VirtualAppliance --next-hop-ip-address 10.20.0.4
az network route-table route create --resource-group udr-test --name route82 --route-table-name RT --address-prefix 10.0.82.0/24 --next-hop-type VirtualAppliance --next-hop-ip-address 10.20.0.4
az network route-table route create --resource-group udr-test --name route83 --route-table-name RT --address-prefix 10.0.83.0/24 --next-hop-type VirtualAppliance --next-hop-ip-address 10.20.0.4
az network route-table route create --resource-group udr-test --name route84 --route-table-name RT --address-prefix 10.0.84.0/24 --next-hop-type VirtualAppliance --next-hop-ip-address 10.20.0.4
az network route-table route create --resource-group udr-test --name route85 --route-table-name RT --address-prefix 10.0.85.0/24 --next-hop-type VirtualAppliance --next-hop-ip-address 10.20.0.4
az network route-table route create --resource-group udr-test --name route86 --route-table-name RT --address-prefix 10.0.86.0/24 --next-hop-type VirtualAppliance --next-hop-ip-address 10.20.0.4
az network route-table route create --resource-group udr-test --name route87 --route-table-name RT --address-prefix 10.0.87.0/24 --next-hop-type VirtualAppliance --next-hop-ip-address 10.20.0.4
az network route-table route create --resource-group udr-test --name route88 --route-table-name RT --address-prefix 10.0.88.0/24 --next-hop-type VirtualAppliance --next-hop-ip-address 10.20.0.4
az network route-table route create --resource-group udr-test --name route89 --route-table-name RT --address-prefix 10.0.89.0/24 --next-hop-type VirtualAppliance --next-hop-ip-address 10.20.0.4
az network route-table route create --resource-group udr-test --name route90 --route-table-name RT --address-prefix 10.0.90.0/24 --next-hop-type VirtualAppliance --next-hop-ip-address 10.20.0.4
az network route-table route create --resource-group udr-test --name route91 --route-table-name RT --address-prefix 10.0.91.0/24 --next-hop-type VirtualAppliance --next-hop-ip-address 10.20.0.4
az network route-table route create --resource-group udr-test --name route92 --route-table-name RT --address-prefix 10.0.92.0/24 --next-hop-type VirtualAppliance --next-hop-ip-address 10.20.0.4
az network route-table route create --resource-group udr-test --name route93 --route-table-name RT --address-prefix 10.0.93.0/24 --next-hop-type VirtualAppliance --next-hop-ip-address 10.20.0.4
az network route-table route create --resource-group udr-test --name route94 --route-table-name RT --address-prefix 10.0.94.0/24 --next-hop-type VirtualAppliance --next-hop-ip-address 10.20.0.4
az network route-table route create --resource-group udr-test --name route95 --route-table-name RT --address-prefix 10.0.95.0/24 --next-hop-type VirtualAppliance --next-hop-ip-address 10.20.0.4
az network route-table route create --resource-group udr-test --name route96 --route-table-name RT --address-prefix 10.0.96.0/24 --next-hop-type VirtualAppliance --next-hop-ip-address 10.20.0.4
az network route-table route create --resource-group udr-test --name route97 --route-table-name RT --address-prefix 10.0.97.0/24 --next-hop-type VirtualAppliance --next-hop-ip-address 10.20.0.4
az network route-table route create --resource-group udr-test --name route98 --route-table-name RT --address-prefix 10.0.98.0/24 --next-hop-type VirtualAppliance --next-hop-ip-address 10.20.0.4
az network route-table route create --resource-group udr-test --name route99 --route-table-name RT --address-prefix 10.0.99.0/24 --next-hop-type VirtualAppliance --next-hop-ip-address 10.20.0.4
az network route-table route create --resource-group udr-test --name route100 --route-table-name RT --address-prefix 10.0.100.0/24 --next-hop-type VirtualAppliance --next-hop-ip-address 10.20.0.4
az network route-table route create --resource-group udr-test --name route101 --route-table-name RT --address-prefix 10.0.101.0/24 --next-hop-type VirtualAppliance --next-hop-ip-address 10.20.0.4
az network route-table route create --resource-group udr-test --name route102 --route-table-name RT --address-prefix 10.0.102.0/24 --next-hop-type VirtualAppliance --next-hop-ip-address 10.20.0.4
az network route-table route create --resource-group udr-test --name route103 --route-table-name RT --address-prefix 10.0.103.0/24 --next-hop-type VirtualAppliance --next-hop-ip-address 10.20.0.4
az network route-table route create --resource-group udr-test --name route104 --route-table-name RT --address-prefix 10.0.104.0/24 --next-hop-type VirtualAppliance --next-hop-ip-address 10.20.0.4
az network route-table route create --resource-group udr-test --name route105 --route-table-name RT --address-prefix 10.0.105.0/24 --next-hop-type VirtualAppliance --next-hop-ip-address 10.20.0.4
az network route-table route create --resource-group udr-test --name route106 --route-table-name RT --address-prefix 10.0.106.0/24 --next-hop-type VirtualAppliance --next-hop-ip-address 10.20.0.4
az network route-table route create --resource-group udr-test --name route107 --route-table-name RT --address-prefix 10.0.107.0/24 --next-hop-type VirtualAppliance --next-hop-ip-address 10.20.0.4
az network route-table route create --resource-group udr-test --name route108 --route-table-name RT --address-prefix 10.0.108.0/24 --next-hop-type VirtualAppliance --next-hop-ip-address 10.20.0.4
az network route-table route create --resource-group udr-test --name route109 --route-table-name RT --address-prefix 10.0.109.0/24 --next-hop-type VirtualAppliance --next-hop-ip-address 10.20.0.4
az network route-table route create --resource-group udr-test --name route110 --route-table-name RT --address-prefix 10.0.110.0/24 --next-hop-type VirtualAppliance --next-hop-ip-address 10.20.0.4
az network route-table route create --resource-group udr-test --name route111 --route-table-name RT --address-prefix 10.0.111.0/24 --next-hop-type VirtualAppliance --next-hop-ip-address 10.20.0.4
az network route-table route create --resource-group udr-test --name route112 --route-table-name RT --address-prefix 10.0.112.0/24 --next-hop-type VirtualAppliance --next-hop-ip-address 10.20.0.4
az network route-table route create --resource-group udr-test --name route113 --route-table-name RT --address-prefix 10.0.113.0/24 --next-hop-type VirtualAppliance --next-hop-ip-address 10.20.0.4
az network route-table route create --resource-group udr-test --name route114 --route-table-name RT --address-prefix 10.0.114.0/24 --next-hop-type VirtualAppliance --next-hop-ip-address 10.20.0.4
az network route-table route create --resource-group udr-test --name route115 --route-table-name RT --address-prefix 10.0.115.0/24 --next-hop-type VirtualAppliance --next-hop-ip-address 10.20.0.4
az network route-table route create --resource-group udr-test --name route116 --route-table-name RT --address-prefix 10.0.116.0/24 --next-hop-type VirtualAppliance --next-hop-ip-address 10.20.0.4
az network route-table route create --resource-group udr-test --name route117 --route-table-name RT --address-prefix 10.0.117.0/24 --next-hop-type VirtualAppliance --next-hop-ip-address 10.20.0.4
az network route-table route create --resource-group udr-test --name route118 --route-table-name RT --address-prefix 10.0.118.0/24 --next-hop-type VirtualAppliance --next-hop-ip-address 10.20.0.4
az network route-table route create --resource-group udr-test --name route119 --route-table-name RT --address-prefix 10.0.119.0/24 --next-hop-type VirtualAppliance --next-hop-ip-address 10.20.0.4
az network route-table route create --resource-group udr-test --name route120 --route-table-name RT --address-prefix 10.0.120.0/24 --next-hop-type VirtualAppliance --next-hop-ip-address 10.20.0.4
az network route-table route create --resource-group udr-test --name route121 --route-table-name RT --address-prefix 10.0.121.0/24 --next-hop-type VirtualAppliance --next-hop-ip-address 10.20.0.4
az network route-table route create --resource-group udr-test --name route122 --route-table-name RT --address-prefix 10.0.122.0/24 --next-hop-type VirtualAppliance --next-hop-ip-address 10.20.0.4
az network route-table route create --resource-group udr-test --name route123 --route-table-name RT --address-prefix 10.0.123.0/24 --next-hop-type VirtualAppliance --next-hop-ip-address 10.20.0.4
az network route-table route create --resource-group udr-test --name route124 --route-table-name RT --address-prefix 10.0.124.0/24 --next-hop-type VirtualAppliance --next-hop-ip-address 10.20.0.4
az network route-table route create --resource-group udr-test --name route125 --route-table-name RT --address-prefix 10.0.125.0/24 --next-hop-type VirtualAppliance --next-hop-ip-address 10.20.0.4
az network route-table route create --resource-group udr-test --name route126 --route-table-name RT --address-prefix 10.0.126.0/24 --next-hop-type VirtualAppliance --next-hop-ip-address 10.20.0.4
az network route-table route create --resource-group udr-test --name route127 --route-table-name RT --address-prefix 10.0.127.0/24 --next-hop-type VirtualAppliance --next-hop-ip-address 10.20.0.4
az network route-table route create --resource-group udr-test --name route128 --route-table-name RT --address-prefix 10.0.128.0/24 --next-hop-type VirtualAppliance --next-hop-ip-address 10.20.0.4
az network route-table route create --resource-group udr-test --name route129 --route-table-name RT --address-prefix 10.0.129.0/24 --next-hop-type VirtualAppliance --next-hop-ip-address 10.20.0.4
az network route-table route create --resource-group udr-test --name route130 --route-table-name RT --address-prefix 10.0.130.0/24 --next-hop-type VirtualAppliance --next-hop-ip-address 10.20.0.4
az network route-table route create --resource-group udr-test --name route131 --route-table-name RT --address-prefix 10.0.131.0/24 --next-hop-type VirtualAppliance --next-hop-ip-address 10.20.0.4
az network route-table route create --resource-group udr-test --name route132 --route-table-name RT --address-prefix 10.0.132.0/24 --next-hop-type VirtualAppliance --next-hop-ip-address 10.20.0.4
az network route-table route create --resource-group udr-test --name route133 --route-table-name RT --address-prefix 10.0.133.0/24 --next-hop-type VirtualAppliance --next-hop-ip-address 10.20.0.4
az network route-table route create --resource-group udr-test --name route134 --route-table-name RT --address-prefix 10.0.134.0/24 --next-hop-type VirtualAppliance --next-hop-ip-address 10.20.0.4
az network route-table route create --resource-group udr-test --name route135 --route-table-name RT --address-prefix 10.0.135.0/24 --next-hop-type VirtualAppliance --next-hop-ip-address 10.20.0.4
az network route-table route create --resource-group udr-test --name route136 --route-table-name RT --address-prefix 10.0.136.0/24 --next-hop-type VirtualAppliance --next-hop-ip-address 10.20.0.4
az network route-table route create --resource-group udr-test --name route137 --route-table-name RT --address-prefix 10.0.137.0/24 --next-hop-type VirtualAppliance --next-hop-ip-address 10.20.0.4
az network route-table route create --resource-group udr-test --name route138 --route-table-name RT --address-prefix 10.0.138.0/24 --next-hop-type VirtualAppliance --next-hop-ip-address 10.20.0.4
az network route-table route create --resource-group udr-test --name route139 --route-table-name RT --address-prefix 10.0.139.0/24 --next-hop-type VirtualAppliance --next-hop-ip-address 10.20.0.4
az network route-table route create --resource-group udr-test --name route140 --route-table-name RT --address-prefix 10.0.140.0/24 --next-hop-type VirtualAppliance --next-hop-ip-address 10.20.0.4
az network route-table route create --resource-group udr-test --name route141 --route-table-name RT --address-prefix 10.0.141.0/24 --next-hop-type VirtualAppliance --next-hop-ip-address 10.20.0.4
az network route-table route create --resource-group udr-test --name route142 --route-table-name RT --address-prefix 10.0.142.0/24 --next-hop-type VirtualAppliance --next-hop-ip-address 10.20.0.4
az network route-table route create --resource-group udr-test --name route143 --route-table-name RT --address-prefix 10.0.143.0/24 --next-hop-type VirtualAppliance --next-hop-ip-address 10.20.0.4
az network route-table route create --resource-group udr-test --name route144 --route-table-name RT --address-prefix 10.0.144.0/24 --next-hop-type VirtualAppliance --next-hop-ip-address 10.20.0.4
az network route-table route create --resource-group udr-test --name route145 --route-table-name RT --address-prefix 10.0.145.0/24 --next-hop-type VirtualAppliance --next-hop-ip-address 10.20.0.4
az network route-table route create --resource-group udr-test --name route146 --route-table-name RT --address-prefix 10.0.146.0/24 --next-hop-type VirtualAppliance --next-hop-ip-address 10.20.0.4
az network route-table route create --resource-group udr-test --name route147 --route-table-name RT --address-prefix 10.0.147.0/24 --next-hop-type VirtualAppliance --next-hop-ip-address 10.20.0.4
az network route-table route create --resource-group udr-test --name route148 --route-table-name RT --address-prefix 10.0.148.0/24 --next-hop-type VirtualAppliance --next-hop-ip-address 10.20.0.4
az network route-table route create --resource-group udr-test --name route149 --route-table-name RT --address-prefix 10.0.149.0/24 --next-hop-type VirtualAppliance --next-hop-ip-address 10.20.0.4
az network route-table route create --resource-group udr-test --name route150 --route-table-name RT --address-prefix 10.0.150.0/24 --next-hop-type VirtualAppliance --next-hop-ip-address 10.20.0.4
az network route-table route create --resource-group udr-test --name route151 --route-table-name RT --address-prefix 10.0.151.0/24 --next-hop-type VirtualAppliance --next-hop-ip-address 10.20.0.4
az network route-table route create --resource-group udr-test --name route152 --route-table-name RT --address-prefix 10.0.152.0/24 --next-hop-type VirtualAppliance --next-hop-ip-address 10.20.0.4
az network route-table route create --resource-group udr-test --name route153 --route-table-name RT --address-prefix 10.0.153.0/24 --next-hop-type VirtualAppliance --next-hop-ip-address 10.20.0.4
az network route-table route create --resource-group udr-test --name route154 --route-table-name RT --address-prefix 10.0.154.0/24 --next-hop-type VirtualAppliance --next-hop-ip-address 10.20.0.4
az network route-table route create --resource-group udr-test --name route155 --route-table-name RT --address-prefix 10.0.155.0/24 --next-hop-type VirtualAppliance --next-hop-ip-address 10.20.0.4
az network route-table route create --resource-group udr-test --name route156 --route-table-name RT --address-prefix 10.0.156.0/24 --next-hop-type VirtualAppliance --next-hop-ip-address 10.20.0.4
az network route-table route create --resource-group udr-test --name route157 --route-table-name RT --address-prefix 10.0.157.0/24 --next-hop-type VirtualAppliance --next-hop-ip-address 10.20.0.4
az network route-table route create --resource-group udr-test --name route158 --route-table-name RT --address-prefix 10.0.158.0/24 --next-hop-type VirtualAppliance --next-hop-ip-address 10.20.0.4
az network route-table route create --resource-group udr-test --name route159 --route-table-name RT --address-prefix 10.0.159.0/24 --next-hop-type VirtualAppliance --next-hop-ip-address 10.20.0.4
az network route-table route create --resource-group udr-test --name route160 --route-table-name RT --address-prefix 10.0.160.0/24 --next-hop-type VirtualAppliance --next-hop-ip-address 10.20.0.4
az network route-table route create --resource-group udr-test --name route161 --route-table-name RT --address-prefix 10.0.161.0/24 --next-hop-type VirtualAppliance --next-hop-ip-address 10.20.0.4
az network route-table route create --resource-group udr-test --name route162 --route-table-name RT --address-prefix 10.0.162.0/24 --next-hop-type VirtualAppliance --next-hop-ip-address 10.20.0.4
az network route-table route create --resource-group udr-test --name route163 --route-table-name RT --address-prefix 10.0.163.0/24 --next-hop-type VirtualAppliance --next-hop-ip-address 10.20.0.4
az network route-table route create --resource-group udr-test --name route164 --route-table-name RT --address-prefix 10.0.164.0/24 --next-hop-type VirtualAppliance --next-hop-ip-address 10.20.0.4
az network route-table route create --resource-group udr-test --name route165 --route-table-name RT --address-prefix 10.0.165.0/24 --next-hop-type VirtualAppliance --next-hop-ip-address 10.20.0.4
az network route-table route create --resource-group udr-test --name route166 --route-table-name RT --address-prefix 10.0.166.0/24 --next-hop-type VirtualAppliance --next-hop-ip-address 10.20.0.4
az network route-table route create --resource-group udr-test --name route167 --route-table-name RT --address-prefix 10.0.167.0/24 --next-hop-type VirtualAppliance --next-hop-ip-address 10.20.0.4
az network route-table route create --resource-group udr-test --name route168 --route-table-name RT --address-prefix 10.0.168.0/24 --next-hop-type VirtualAppliance --next-hop-ip-address 10.20.0.4
az network route-table route create --resource-group udr-test --name route169 --route-table-name RT --address-prefix 10.0.169.0/24 --next-hop-type VirtualAppliance --next-hop-ip-address 10.20.0.4
az network route-table route create --resource-group udr-test --name route170 --route-table-name RT --address-prefix 10.0.170.0/24 --next-hop-type VirtualAppliance --next-hop-ip-address 10.20.0.4
az network route-table route create --resource-group udr-test --name route171 --route-table-name RT --address-prefix 10.0.171.0/24 --next-hop-type VirtualAppliance --next-hop-ip-address 10.20.0.4
az network route-table route create --resource-group udr-test --name route172 --route-table-name RT --address-prefix 10.0.172.0/24 --next-hop-type VirtualAppliance --next-hop-ip-address 10.20.0.4
az network route-table route create --resource-group udr-test --name route173 --route-table-name RT --address-prefix 10.0.173.0/24 --next-hop-type VirtualAppliance --next-hop-ip-address 10.20.0.4
az network route-table route create --resource-group udr-test --name route174 --route-table-name RT --address-prefix 10.0.174.0/24 --next-hop-type VirtualAppliance --next-hop-ip-address 10.20.0.4
az network route-table route create --resource-group udr-test --name route175 --route-table-name RT --address-prefix 10.0.175.0/24 --next-hop-type VirtualAppliance --next-hop-ip-address 10.20.0.4
az network route-table route create --resource-group udr-test --name route176 --route-table-name RT --address-prefix 10.0.176.0/24 --next-hop-type VirtualAppliance --next-hop-ip-address 10.20.0.4
az network route-table route create --resource-group udr-test --name route177 --route-table-name RT --address-prefix 10.0.177.0/24 --next-hop-type VirtualAppliance --next-hop-ip-address 10.20.0.4
az network route-table route create --resource-group udr-test --name route178 --route-table-name RT --address-prefix 10.0.178.0/24 --next-hop-type VirtualAppliance --next-hop-ip-address 10.20.0.4
az network route-table route create --resource-group udr-test --name route179 --route-table-name RT --address-prefix 10.0.179.0/24 --next-hop-type VirtualAppliance --next-hop-ip-address 10.20.0.4
az network route-table route create --resource-group udr-test --name route180 --route-table-name RT --address-prefix 10.0.180.0/24 --next-hop-type VirtualAppliance --next-hop-ip-address 10.20.0.4
az network route-table route create --resource-group udr-test --name route181 --route-table-name RT --address-prefix 10.0.181.0/24 --next-hop-type VirtualAppliance --next-hop-ip-address 10.20.0.4
az network route-table route create --resource-group udr-test --name route182 --route-table-name RT --address-prefix 10.0.182.0/24 --next-hop-type VirtualAppliance --next-hop-ip-address 10.20.0.4
az network route-table route create --resource-group udr-test --name route183 --route-table-name RT --address-prefix 10.0.183.0/24 --next-hop-type VirtualAppliance --next-hop-ip-address 10.20.0.4
az network route-table route create --resource-group udr-test --name route184 --route-table-name RT --address-prefix 10.0.184.0/24 --next-hop-type VirtualAppliance --next-hop-ip-address 10.20.0.4
az network route-table route create --resource-group udr-test --name route185 --route-table-name RT --address-prefix 10.0.185.0/24 --next-hop-type VirtualAppliance --next-hop-ip-address 10.20.0.4
az network route-table route create --resource-group udr-test --name route186 --route-table-name RT --address-prefix 10.0.186.0/24 --next-hop-type VirtualAppliance --next-hop-ip-address 10.20.0.4
az network route-table route create --resource-group udr-test --name route187 --route-table-name RT --address-prefix 10.0.187.0/24 --next-hop-type VirtualAppliance --next-hop-ip-address 10.20.0.4
az network route-table route create --resource-group udr-test --name route188 --route-table-name RT --address-prefix 10.0.188.0/24 --next-hop-type VirtualAppliance --next-hop-ip-address 10.20.0.4
az network route-table route create --resource-group udr-test --name route189 --route-table-name RT --address-prefix 10.0.189.0/24 --next-hop-type VirtualAppliance --next-hop-ip-address 10.20.0.4
az network route-table route create --resource-group udr-test --name route190 --route-table-name RT --address-prefix 10.0.190.0/24 --next-hop-type VirtualAppliance --next-hop-ip-address 10.20.0.4
az network route-table route create --resource-group udr-test --name route191 --route-table-name RT --address-prefix 10.0.191.0/24 --next-hop-type VirtualAppliance --next-hop-ip-address 10.20.0.4
az network route-table route create --resource-group udr-test --name route192 --route-table-name RT --address-prefix 10.0.192.0/24 --next-hop-type VirtualAppliance --next-hop-ip-address 10.20.0.4
az network route-table route create --resource-group udr-test --name route193 --route-table-name RT --address-prefix 10.0.193.0/24 --next-hop-type VirtualAppliance --next-hop-ip-address 10.20.0.4
az network route-table route create --resource-group udr-test --name route194 --route-table-name RT --address-prefix 10.0.194.0/24 --next-hop-type VirtualAppliance --next-hop-ip-address 10.20.0.4
az network route-table route create --resource-group udr-test --name route195 --route-table-name RT --address-prefix 10.0.195.0/24 --next-hop-type VirtualAppliance --next-hop-ip-address 10.20.0.4
az network route-table route create --resource-group udr-test --name route196 --route-table-name RT --address-prefix 10.0.196.0/24 --next-hop-type VirtualAppliance --next-hop-ip-address 10.20.0.4
az network route-table route create --resource-group udr-test --name route197 --route-table-name RT --address-prefix 10.0.197.0/24 --next-hop-type VirtualAppliance --next-hop-ip-address 10.20.0.4
az network route-table route create --resource-group udr-test --name route198 --route-table-name RT --address-prefix 10.0.198.0/24 --next-hop-type VirtualAppliance --next-hop-ip-address 10.20.0.4
az network route-table route create --resource-group udr-test --name route199 --route-table-name RT --address-prefix 10.0.199.0/24 --next-hop-type VirtualAppliance --next-hop-ip-address 10.20.0.4
az network route-table route create --resource-group udr-test --name route200 --route-table-name RT --address-prefix 10.0.200.0/24 --next-hop-type VirtualAppliance --next-hop-ip-address 10.20.0.4
az network route-table route create --resource-group udr-test --name route201 --route-table-name RT --address-prefix 10.0.201.0/24 --next-hop-type VirtualAppliance --next-hop-ip-address 10.20.0.4
az network route-table route create --resource-group udr-test --name route202 --route-table-name RT --address-prefix 10.0.202.0/24 --next-hop-type VirtualAppliance --next-hop-ip-address 10.20.0.4
az network route-table route create --resource-group udr-test --name route203 --route-table-name RT --address-prefix 10.0.203.0/24 --next-hop-type VirtualAppliance --next-hop-ip-address 10.20.0.4
az network route-table route create --resource-group udr-test --name route204 --route-table-name RT --address-prefix 10.0.204.0/24 --next-hop-type VirtualAppliance --next-hop-ip-address 10.20.0.4
az network route-table route create --resource-group udr-test --name route205 --route-table-name RT --address-prefix 10.0.205.0/24 --next-hop-type VirtualAppliance --next-hop-ip-address 10.20.0.4
az network route-table route create --resource-group udr-test --name route206 --route-table-name RT --address-prefix 10.0.206.0/24 --next-hop-type VirtualAppliance --next-hop-ip-address 10.20.0.4
az network route-table route create --resource-group udr-test --name route207 --route-table-name RT --address-prefix 10.0.207.0/24 --next-hop-type VirtualAppliance --next-hop-ip-address 10.20.0.4
az network route-table route create --resource-group udr-test --name route208 --route-table-name RT --address-prefix 10.0.208.0/24 --next-hop-type VirtualAppliance --next-hop-ip-address 10.20.0.4
az network route-table route create --resource-group udr-test --name route209 --route-table-name RT --address-prefix 10.0.209.0/24 --next-hop-type VirtualAppliance --next-hop-ip-address 10.20.0.4
az network route-table route create --resource-group udr-test --name route210 --route-table-name RT --address-prefix 10.0.210.0/24 --next-hop-type VirtualAppliance --next-hop-ip-address 10.20.0.4
az network route-table route create --resource-group udr-test --name route211 --route-table-name RT --address-prefix 10.0.211.0/24 --next-hop-type VirtualAppliance --next-hop-ip-address 10.20.0.4
az network route-table route create --resource-group udr-test --name route212 --route-table-name RT --address-prefix 10.0.212.0/24 --next-hop-type VirtualAppliance --next-hop-ip-address 10.20.0.4
az network route-table route create --resource-group udr-test --name route213 --route-table-name RT --address-prefix 10.0.213.0/24 --next-hop-type VirtualAppliance --next-hop-ip-address 10.20.0.4
az network route-table route create --resource-group udr-test --name route214 --route-table-name RT --address-prefix 10.0.214.0/24 --next-hop-type VirtualAppliance --next-hop-ip-address 10.20.0.4
az network route-table route create --resource-group udr-test --name route215 --route-table-name RT --address-prefix 10.0.215.0/24 --next-hop-type VirtualAppliance --next-hop-ip-address 10.20.0.4
az network route-table route create --resource-group udr-test --name route216 --route-table-name RT --address-prefix 10.0.216.0/24 --next-hop-type VirtualAppliance --next-hop-ip-address 10.20.0.4
az network route-table route create --resource-group udr-test --name route217 --route-table-name RT --address-prefix 10.0.217.0/24 --next-hop-type VirtualAppliance --next-hop-ip-address 10.20.0.4
az network route-table route create --resource-group udr-test --name route218 --route-table-name RT --address-prefix 10.0.218.0/24 --next-hop-type VirtualAppliance --next-hop-ip-address 10.20.0.4
az network route-table route create --resource-group udr-test --name route219 --route-table-name RT --address-prefix 10.0.219.0/24 --next-hop-type VirtualAppliance --next-hop-ip-address 10.20.0.4
az network route-table route create --resource-group udr-test --name route220 --route-table-name RT --address-prefix 10.0.220.0/24 --next-hop-type VirtualAppliance --next-hop-ip-address 10.20.0.4
az network route-table route create --resource-group udr-test --name route221 --route-table-name RT --address-prefix 10.0.221.0/24 --next-hop-type VirtualAppliance --next-hop-ip-address 10.20.0.4
az network route-table route create --resource-group udr-test --name route222 --route-table-name RT --address-prefix 10.0.222.0/24 --next-hop-type VirtualAppliance --next-hop-ip-address 10.20.0.4
az network route-table route create --resource-group udr-test --name route223 --route-table-name RT --address-prefix 10.0.223.0/24 --next-hop-type VirtualAppliance --next-hop-ip-address 10.20.0.4
az network route-table route create --resource-group udr-test --name route224 --route-table-name RT --address-prefix 10.0.224.0/24 --next-hop-type VirtualAppliance --next-hop-ip-address 10.20.0.4
az network route-table route create --resource-group udr-test --name route225 --route-table-name RT --address-prefix 10.0.225.0/24 --next-hop-type VirtualAppliance --next-hop-ip-address 10.20.0.4
az network route-table route create --resource-group udr-test --name route226 --route-table-name RT --address-prefix 10.0.226.0/24 --next-hop-type VirtualAppliance --next-hop-ip-address 10.20.0.4
az network route-table route create --resource-group udr-test --name route227 --route-table-name RT --address-prefix 10.0.227.0/24 --next-hop-type VirtualAppliance --next-hop-ip-address 10.20.0.4
az network route-table route create --resource-group udr-test --name route228 --route-table-name RT --address-prefix 10.0.228.0/24 --next-hop-type VirtualAppliance --next-hop-ip-address 10.20.0.4
az network route-table route create --resource-group udr-test --name route229 --route-table-name RT --address-prefix 10.0.229.0/24 --next-hop-type VirtualAppliance --next-hop-ip-address 10.20.0.4
az network route-table route create --resource-group udr-test --name route230 --route-table-name RT --address-prefix 10.0.230.0/24 --next-hop-type VirtualAppliance --next-hop-ip-address 10.20.0.4
az network route-table route create --resource-group udr-test --name route231 --route-table-name RT --address-prefix 10.0.231.0/24 --next-hop-type VirtualAppliance --next-hop-ip-address 10.20.0.4
az network route-table route create --resource-group udr-test --name route232 --route-table-name RT --address-prefix 10.0.232.0/24 --next-hop-type VirtualAppliance --next-hop-ip-address 10.20.0.4
az network route-table route create --resource-group udr-test --name route233 --route-table-name RT --address-prefix 10.0.233.0/24 --next-hop-type VirtualAppliance --next-hop-ip-address 10.20.0.4
az network route-table route create --resource-group udr-test --name route234 --route-table-name RT --address-prefix 10.0.234.0/24 --next-hop-type VirtualAppliance --next-hop-ip-address 10.20.0.4
az network route-table route create --resource-group udr-test --name route235 --route-table-name RT --address-prefix 10.0.235.0/24 --next-hop-type VirtualAppliance --next-hop-ip-address 10.20.0.4
az network route-table route create --resource-group udr-test --name route236 --route-table-name RT --address-prefix 10.0.236.0/24 --next-hop-type VirtualAppliance --next-hop-ip-address 10.20.0.4
az network route-table route create --resource-group udr-test --name route237 --route-table-name RT --address-prefix 10.0.237.0/24 --next-hop-type VirtualAppliance --next-hop-ip-address 10.20.0.4
az network route-table route create --resource-group udr-test --name route238 --route-table-name RT --address-prefix 10.0.238.0/24 --next-hop-type VirtualAppliance --next-hop-ip-address 10.20.0.4
az network route-table route create --resource-group udr-test --name route239 --route-table-name RT --address-prefix 10.0.239.0/24 --next-hop-type VirtualAppliance --next-hop-ip-address 10.20.0.4
az network route-table route create --resource-group udr-test --name route240 --route-table-name RT --address-prefix 10.0.240.0/24 --next-hop-type VirtualAppliance --next-hop-ip-address 10.20.0.4
az network route-table route create --resource-group udr-test --name route241 --route-table-name RT --address-prefix 10.0.241.0/24 --next-hop-type VirtualAppliance --next-hop-ip-address 10.20.0.4
az network route-table route create --resource-group udr-test --name route242 --route-table-name RT --address-prefix 10.0.242.0/24 --next-hop-type VirtualAppliance --next-hop-ip-address 10.20.0.4
az network route-table route create --resource-group udr-test --name route243 --route-table-name RT --address-prefix 10.0.243.0/24 --next-hop-type VirtualAppliance --next-hop-ip-address 10.20.0.4
az network route-table route create --resource-group udr-test --name route244 --route-table-name RT --address-prefix 10.0.244.0/24 --next-hop-type VirtualAppliance --next-hop-ip-address 10.20.0.4
az network route-table route create --resource-group udr-test --name route245 --route-table-name RT --address-prefix 10.0.245.0/24 --next-hop-type VirtualAppliance --next-hop-ip-address 10.20.0.4
az network route-table route create --resource-group udr-test --name route246 --route-table-name RT --address-prefix 10.0.246.0/24 --next-hop-type VirtualAppliance --next-hop-ip-address 10.20.0.4
az network route-table route create --resource-group udr-test --name route247 --route-table-name RT --address-prefix 10.0.247.0/24 --next-hop-type VirtualAppliance --next-hop-ip-address 10.20.0.4
az network route-table route create --resource-group udr-test --name route248 --route-table-name RT --address-prefix 10.0.248.0/24 --next-hop-type VirtualAppliance --next-hop-ip-address 10.20.0.4
az network route-table route create --resource-group udr-test --name route249 --route-table-name RT --address-prefix 10.0.249.0/24 --next-hop-type VirtualAppliance --next-hop-ip-address 10.20.0.4
az network route-table route create --resource-group udr-test --name route0 --route-table-name RT --address-prefix 10.1.0.0/24 --next-hop-type VirtualAppliance --next-hop-ip-address 10.20.0.4
az network route-table route create --resource-group udr-test --name route1 --route-table-name RT --address-prefix 10.1.1.0/24 --next-hop-type VirtualAppliance --next-hop-ip-address 10.20.0.4
az network route-table route create --resource-group udr-test --name route2 --route-table-name RT --address-prefix 10.1.2.0/24 --next-hop-type VirtualAppliance --next-hop-ip-address 10.20.0.4
az network route-table route create --resource-group udr-test --name route3 --route-table-name RT --address-prefix 10.1.3.0/24 --next-hop-type VirtualAppliance --next-hop-ip-address 10.20.0.4
az network route-table route create --resource-group udr-test --name route4 --route-table-name RT --address-prefix 10.1.4.0/24 --next-hop-type VirtualAppliance --next-hop-ip-address 10.20.0.4
az network route-table route create --resource-group udr-test --name route5 --route-table-name RT --address-prefix 10.1.5.0/24 --next-hop-type VirtualAppliance --next-hop-ip-address 10.20.0.4
az network route-table route create --resource-group udr-test --name route6 --route-table-name RT --address-prefix 10.1.6.0/24 --next-hop-type VirtualAppliance --next-hop-ip-address 10.20.0.4
az network route-table route create --resource-group udr-test --name route7 --route-table-name RT --address-prefix 10.1.7.0/24 --next-hop-type VirtualAppliance --next-hop-ip-address 10.20.0.4
az network route-table route create --resource-group udr-test --name route8 --route-table-name RT --address-prefix 10.1.8.0/24 --next-hop-type VirtualAppliance --next-hop-ip-address 10.20.0.4
az network route-table route create --resource-group udr-test --name route9 --route-table-name RT --address-prefix 10.1.9.0/24 --next-hop-type VirtualAppliance --next-hop-ip-address 10.20.0.4
az network route-table route create --resource-group udr-test --name route10 --route-table-name RT --address-prefix 10.1.10.0/24 --next-hop-type VirtualAppliance --next-hop-ip-address 10.20.0.4
az network route-table route create --resource-group udr-test --name route11 --route-table-name RT --address-prefix 10.1.11.0/24 --next-hop-type VirtualAppliance --next-hop-ip-address 10.20.0.4
az network route-table route create --resource-group udr-test --name route12 --route-table-name RT --address-prefix 10.1.12.0/24 --next-hop-type VirtualAppliance --next-hop-ip-address 10.20.0.4
az network route-table route create --resource-group udr-test --name route13 --route-table-name RT --address-prefix 10.1.13.0/24 --next-hop-type VirtualAppliance --next-hop-ip-address 10.20.0.4
az network route-table route create --resource-group udr-test --name route14 --route-table-name RT --address-prefix 10.1.14.0/24 --next-hop-type VirtualAppliance --next-hop-ip-address 10.20.0.4
az network route-table route create --resource-group udr-test --name route15 --route-table-name RT --address-prefix 10.1.15.0/24 --next-hop-type VirtualAppliance --next-hop-ip-address 10.20.0.4
az network route-table route create --resource-group udr-test --name route16 --route-table-name RT --address-prefix 10.1.16.0/24 --next-hop-type VirtualAppliance --next-hop-ip-address 10.20.0.4
az network route-table route create --resource-group udr-test --name route17 --route-table-name RT --address-prefix 10.1.17.0/24 --next-hop-type VirtualAppliance --next-hop-ip-address 10.20.0.4
az network route-table route create --resource-group udr-test --name route18 --route-table-name RT --address-prefix 10.1.18.0/24 --next-hop-type VirtualAppliance --next-hop-ip-address 10.20.0.4
az network route-table route create --resource-group udr-test --name route19 --route-table-name RT --address-prefix 10.1.19.0/24 --next-hop-type VirtualAppliance --next-hop-ip-address 10.20.0.4
az network route-table route create --resource-group udr-test --name route20 --route-table-name RT --address-prefix 10.1.20.0/24 --next-hop-type VirtualAppliance --next-hop-ip-address 10.20.0.4
az network route-table route create --resource-group udr-test --name route21 --route-table-name RT --address-prefix 10.1.21.0/24 --next-hop-type VirtualAppliance --next-hop-ip-address 10.20.0.4
az network route-table route create --resource-group udr-test --name route22 --route-table-name RT --address-prefix 10.1.22.0/24 --next-hop-type VirtualAppliance --next-hop-ip-address 10.20.0.4
az network route-table route create --resource-group udr-test --name route23 --route-table-name RT --address-prefix 10.1.23.0/24 --next-hop-type VirtualAppliance --next-hop-ip-address 10.20.0.4
az network route-table route create --resource-group udr-test --name route24 --route-table-name RT --address-prefix 10.1.24.0/24 --next-hop-type VirtualAppliance --next-hop-ip-address 10.20.0.4
az network route-table route create --resource-group udr-test --name route25 --route-table-name RT --address-prefix 10.1.25.0/24 --next-hop-type VirtualAppliance --next-hop-ip-address 10.20.0.4
az network route-table route create --resource-group udr-test --name route26 --route-table-name RT --address-prefix 10.1.26.0/24 --next-hop-type VirtualAppliance --next-hop-ip-address 10.20.0.4
az network route-table route create --resource-group udr-test --name route27 --route-table-name RT --address-prefix 10.1.27.0/24 --next-hop-type VirtualAppliance --next-hop-ip-address 10.20.0.4
az network route-table route create --resource-group udr-test --name route28 --route-table-name RT --address-prefix 10.1.28.0/24 --next-hop-type VirtualAppliance --next-hop-ip-address 10.20.0.4
az network route-table route create --resource-group udr-test --name route29 --route-table-name RT --address-prefix 10.1.29.0/24 --next-hop-type VirtualAppliance --next-hop-ip-address 10.20.0.4
az network route-table route create --resource-group udr-test --name route30 --route-table-name RT --address-prefix 10.1.30.0/24 --next-hop-type VirtualAppliance --next-hop-ip-address 10.20.0.4
az network route-table route create --resource-group udr-test --name route31 --route-table-name RT --address-prefix 10.1.31.0/24 --next-hop-type VirtualAppliance --next-hop-ip-address 10.20.0.4
az network route-table route create --resource-group udr-test --name route32 --route-table-name RT --address-prefix 10.1.32.0/24 --next-hop-type VirtualAppliance --next-hop-ip-address 10.20.0.4
az network route-table route create --resource-group udr-test --name route33 --route-table-name RT --address-prefix 10.1.33.0/24 --next-hop-type VirtualAppliance --next-hop-ip-address 10.20.0.4
az network route-table route create --resource-group udr-test --name route34 --route-table-name RT --address-prefix 10.1.34.0/24 --next-hop-type VirtualAppliance --next-hop-ip-address 10.20.0.4
az network route-table route create --resource-group udr-test --name route35 --route-table-name RT --address-prefix 10.1.35.0/24 --next-hop-type VirtualAppliance --next-hop-ip-address 10.20.0.4
az network route-table route create --resource-group udr-test --name route36 --route-table-name RT --address-prefix 10.1.36.0/24 --next-hop-type VirtualAppliance --next-hop-ip-address 10.20.0.4
az network route-table route create --resource-group udr-test --name route37 --route-table-name RT --address-prefix 10.1.37.0/24 --next-hop-type VirtualAppliance --next-hop-ip-address 10.20.0.4
az network route-table route create --resource-group udr-test --name route38 --route-table-name RT --address-prefix 10.1.38.0/24 --next-hop-type VirtualAppliance --next-hop-ip-address 10.20.0.4
az network route-table route create --resource-group udr-test --name route39 --route-table-name RT --address-prefix 10.1.39.0/24 --next-hop-type VirtualAppliance --next-hop-ip-address 10.20.0.4
az network route-table route create --resource-group udr-test --name route40 --route-table-name RT --address-prefix 10.1.40.0/24 --next-hop-type VirtualAppliance --next-hop-ip-address 10.20.0.4
az network route-table route create --resource-group udr-test --name route41 --route-table-name RT --address-prefix 10.1.41.0/24 --next-hop-type VirtualAppliance --next-hop-ip-address 10.20.0.4
az network route-table route create --resource-group udr-test --name route42 --route-table-name RT --address-prefix 10.1.42.0/24 --next-hop-type VirtualAppliance --next-hop-ip-address 10.20.0.4
az network route-table route create --resource-group udr-test --name route43 --route-table-name RT --address-prefix 10.1.43.0/24 --next-hop-type VirtualAppliance --next-hop-ip-address 10.20.0.4
az network route-table route create --resource-group udr-test --name route44 --route-table-name RT --address-prefix 10.1.44.0/24 --next-hop-type VirtualAppliance --next-hop-ip-address 10.20.0.4
az network route-table route create --resource-group udr-test --name route45 --route-table-name RT --address-prefix 10.1.45.0/24 --next-hop-type VirtualAppliance --next-hop-ip-address 10.20.0.4
az network route-table route create --resource-group udr-test --name route46 --route-table-name RT --address-prefix 10.1.46.0/24 --next-hop-type VirtualAppliance --next-hop-ip-address 10.20.0.4
az network route-table route create --resource-group udr-test --name route47 --route-table-name RT --address-prefix 10.1.47.0/24 --next-hop-type VirtualAppliance --next-hop-ip-address 10.20.0.4
az network route-table route create --resource-group udr-test --name route48 --route-table-name RT --address-prefix 10.1.48.0/24 --next-hop-type VirtualAppliance --next-hop-ip-address 10.20.0.4
az network route-table route create --resource-group udr-test --name route49 --route-table-name RT --address-prefix 10.1.49.0/24 --next-hop-type VirtualAppliance --next-hop-ip-address 10.20.0.4
az network route-table route create --resource-group udr-test --name route50 --route-table-name RT --address-prefix 10.1.50.0/24 --next-hop-type VirtualAppliance --next-hop-ip-address 10.20.0.4
az network route-table route create --resource-group udr-test --name route51 --route-table-name RT --address-prefix 10.1.51.0/24 --next-hop-type VirtualAppliance --next-hop-ip-address 10.20.0.4
az network route-table route create --resource-group udr-test --name route52 --route-table-name RT --address-prefix 10.1.52.0/24 --next-hop-type VirtualAppliance --next-hop-ip-address 10.20.0.4
az network route-table route create --resource-group udr-test --name route53 --route-table-name RT --address-prefix 10.1.53.0/24 --next-hop-type VirtualAppliance --next-hop-ip-address 10.20.0.4
az network route-table route create --resource-group udr-test --name route54 --route-table-name RT --address-prefix 10.1.54.0/24 --next-hop-type VirtualAppliance --next-hop-ip-address 10.20.0.4
az network route-table route create --resource-group udr-test --name route55 --route-table-name RT --address-prefix 10.1.55.0/24 --next-hop-type VirtualAppliance --next-hop-ip-address 10.20.0.4
az network route-table route create --resource-group udr-test --name route56 --route-table-name RT --address-prefix 10.1.56.0/24 --next-hop-type VirtualAppliance --next-hop-ip-address 10.20.0.4
az network route-table route create --resource-group udr-test --name route57 --route-table-name RT --address-prefix 10.1.57.0/24 --next-hop-type VirtualAppliance --next-hop-ip-address 10.20.0.4
az network route-table route create --resource-group udr-test --name route58 --route-table-name RT --address-prefix 10.1.58.0/24 --next-hop-type VirtualAppliance --next-hop-ip-address 10.20.0.4
az network route-table route create --resource-group udr-test --name route59 --route-table-name RT --address-prefix 10.1.59.0/24 --next-hop-type VirtualAppliance --next-hop-ip-address 10.20.0.4
az network route-table route create --resource-group udr-test --name route60 --route-table-name RT --address-prefix 10.1.60.0/24 --next-hop-type VirtualAppliance --next-hop-ip-address 10.20.0.4
az network route-table route create --resource-group udr-test --name route61 --route-table-name RT --address-prefix 10.1.61.0/24 --next-hop-type VirtualAppliance --next-hop-ip-address 10.20.0.4
az network route-table route create --resource-group udr-test --name route62 --route-table-name RT --address-prefix 10.1.62.0/24 --next-hop-type VirtualAppliance --next-hop-ip-address 10.20.0.4
az network route-table route create --resource-group udr-test --name route63 --route-table-name RT --address-prefix 10.1.63.0/24 --next-hop-type VirtualAppliance --next-hop-ip-address 10.20.0.4
az network route-table route create --resource-group udr-test --name route64 --route-table-name RT --address-prefix 10.1.64.0/24 --next-hop-type VirtualAppliance --next-hop-ip-address 10.20.0.4
az network route-table route create --resource-group udr-test --name route65 --route-table-name RT --address-prefix 10.1.65.0/24 --next-hop-type VirtualAppliance --next-hop-ip-address 10.20.0.4
az network route-table route create --resource-group udr-test --name route66 --route-table-name RT --address-prefix 10.1.66.0/24 --next-hop-type VirtualAppliance --next-hop-ip-address 10.20.0.4
az network route-table route create --resource-group udr-test --name route67 --route-table-name RT --address-prefix 10.1.67.0/24 --next-hop-type VirtualAppliance --next-hop-ip-address 10.20.0.4
az network route-table route create --resource-group udr-test --name route68 --route-table-name RT --address-prefix 10.1.68.0/24 --next-hop-type VirtualAppliance --next-hop-ip-address 10.20.0.4
az network route-table route create --resource-group udr-test --name route69 --route-table-name RT --address-prefix 10.1.69.0/24 --next-hop-type VirtualAppliance --next-hop-ip-address 10.20.0.4
az network route-table route create --resource-group udr-test --name route70 --route-table-name RT --address-prefix 10.1.70.0/24 --next-hop-type VirtualAppliance --next-hop-ip-address 10.20.0.4
az network route-table route create --resource-group udr-test --name route71 --route-table-name RT --address-prefix 10.1.71.0/24 --next-hop-type VirtualAppliance --next-hop-ip-address 10.20.0.4
az network route-table route create --resource-group udr-test --name route72 --route-table-name RT --address-prefix 10.1.72.0/24 --next-hop-type VirtualAppliance --next-hop-ip-address 10.20.0.4
az network route-table route create --resource-group udr-test --name route73 --route-table-name RT --address-prefix 10.1.73.0/24 --next-hop-type VirtualAppliance --next-hop-ip-address 10.20.0.4
az network route-table route create --resource-group udr-test --name route74 --route-table-name RT --address-prefix 10.1.74.0/24 --next-hop-type VirtualAppliance --next-hop-ip-address 10.20.0.4
az network route-table route create --resource-group udr-test --name route75 --route-table-name RT --address-prefix 10.1.75.0/24 --next-hop-type VirtualAppliance --next-hop-ip-address 10.20.0.4
az network route-table route create --resource-group udr-test --name route76 --route-table-name RT --address-prefix 10.1.76.0/24 --next-hop-type VirtualAppliance --next-hop-ip-address 10.20.0.4
az network route-table route create --resource-group udr-test --name route77 --route-table-name RT --address-prefix 10.1.77.0/24 --next-hop-type VirtualAppliance --next-hop-ip-address 10.20.0.4
az network route-table route create --resource-group udr-test --name route78 --route-table-name RT --address-prefix 10.1.78.0/24 --next-hop-type VirtualAppliance --next-hop-ip-address 10.20.0.4
az network route-table route create --resource-group udr-test --name route79 --route-table-name RT --address-prefix 10.1.79.0/24 --next-hop-type VirtualAppliance --next-hop-ip-address 10.20.0.4
az network route-table route create --resource-group udr-test --name route80 --route-table-name RT --address-prefix 10.1.80.0/24 --next-hop-type VirtualAppliance --next-hop-ip-address 10.20.0.4
az network route-table route create --resource-group udr-test --name route81 --route-table-name RT --address-prefix 10.1.81.0/24 --next-hop-type VirtualAppliance --next-hop-ip-address 10.20.0.4
az network route-table route create --resource-group udr-test --name route82 --route-table-name RT --address-prefix 10.1.82.0/24 --next-hop-type VirtualAppliance --next-hop-ip-address 10.20.0.4
az network route-table route create --resource-group udr-test --name route83 --route-table-name RT --address-prefix 10.1.83.0/24 --next-hop-type VirtualAppliance --next-hop-ip-address 10.20.0.4
az network route-table route create --resource-group udr-test --name route84 --route-table-name RT --address-prefix 10.1.84.0/24 --next-hop-type VirtualAppliance --next-hop-ip-address 10.20.0.4
az network route-table route create --resource-group udr-test --name route85 --route-table-name RT --address-prefix 10.1.85.0/24 --next-hop-type VirtualAppliance --next-hop-ip-address 10.20.0.4
az network route-table route create --resource-group udr-test --name route86 --route-table-name RT --address-prefix 10.1.86.0/24 --next-hop-type VirtualAppliance --next-hop-ip-address 10.20.0.4
az network route-table route create --resource-group udr-test --name route87 --route-table-name RT --address-prefix 10.1.87.0/24 --next-hop-type VirtualAppliance --next-hop-ip-address 10.20.0.4
az network route-table route create --resource-group udr-test --name route88 --route-table-name RT --address-prefix 10.1.88.0/24 --next-hop-type VirtualAppliance --next-hop-ip-address 10.20.0.4
az network route-table route create --resource-group udr-test --name route89 --route-table-name RT --address-prefix 10.1.89.0/24 --next-hop-type VirtualAppliance --next-hop-ip-address 10.20.0.4
az network route-table route create --resource-group udr-test --name route90 --route-table-name RT --address-prefix 10.1.90.0/24 --next-hop-type VirtualAppliance --next-hop-ip-address 10.20.0.4
az network route-table route create --resource-group udr-test --name route91 --route-table-name RT --address-prefix 10.1.91.0/24 --next-hop-type VirtualAppliance --next-hop-ip-address 10.20.0.4
az network route-table route create --resource-group udr-test --name route92 --route-table-name RT --address-prefix 10.1.92.0/24 --next-hop-type VirtualAppliance --next-hop-ip-address 10.20.0.4
az network route-table route create --resource-group udr-test --name route93 --route-table-name RT --address-prefix 10.1.93.0/24 --next-hop-type VirtualAppliance --next-hop-ip-address 10.20.0.4
az network route-table route create --resource-group udr-test --name route94 --route-table-name RT --address-prefix 10.1.94.0/24 --next-hop-type VirtualAppliance --next-hop-ip-address 10.20.0.4
az network route-table route create --resource-group udr-test --name route95 --route-table-name RT --address-prefix 10.1.95.0/24 --next-hop-type VirtualAppliance --next-hop-ip-address 10.20.0.4
az network route-table route create --resource-group udr-test --name route96 --route-table-name RT --address-prefix 10.1.96.0/24 --next-hop-type VirtualAppliance --next-hop-ip-address 10.20.0.4
az network route-table route create --resource-group udr-test --name route97 --route-table-name RT --address-prefix 10.1.97.0/24 --next-hop-type VirtualAppliance --next-hop-ip-address 10.20.0.4
az network route-table route create --resource-group udr-test --name route98 --route-table-name RT --address-prefix 10.1.98.0/24 --next-hop-type VirtualAppliance --next-hop-ip-address 10.20.0.4
az network route-table route create --resource-group udr-test --name route99 --route-table-name RT --address-prefix 10.1.99.0/24 --next-hop-type VirtualAppliance --next-hop-ip-address 10.20.0.4
az network route-table route create --resource-group udr-test --name route100 --route-table-name RT --address-prefix 10.1.100.0/24 --next-hop-type VirtualAppliance --next-hop-ip-address 10.20.0.4
az network route-table route create --resource-group udr-test --name route101 --route-table-name RT --address-prefix 10.1.101.0/24 --next-hop-type VirtualAppliance --next-hop-ip-address 10.20.0.4
az network route-table route create --resource-group udr-test --name route102 --route-table-name RT --address-prefix 10.1.102.0/24 --next-hop-type VirtualAppliance --next-hop-ip-address 10.20.0.4
az network route-table route create --resource-group udr-test --name route103 --route-table-name RT --address-prefix 10.1.103.0/24 --next-hop-type VirtualAppliance --next-hop-ip-address 10.20.0.4
az network route-table route create --resource-group udr-test --name route104 --route-table-name RT --address-prefix 10.1.104.0/24 --next-hop-type VirtualAppliance --next-hop-ip-address 10.20.0.4
az network route-table route create --resource-group udr-test --name route105 --route-table-name RT --address-prefix 10.1.105.0/24 --next-hop-type VirtualAppliance --next-hop-ip-address 10.20.0.4
az network route-table route create --resource-group udr-test --name route106 --route-table-name RT --address-prefix 10.1.106.0/24 --next-hop-type VirtualAppliance --next-hop-ip-address 10.20.0.4
az network route-table route create --resource-group udr-test --name route107 --route-table-name RT --address-prefix 10.1.107.0/24 --next-hop-type VirtualAppliance --next-hop-ip-address 10.20.0.4
az network route-table route create --resource-group udr-test --name route108 --route-table-name RT --address-prefix 10.1.108.0/24 --next-hop-type VirtualAppliance --next-hop-ip-address 10.20.0.4
az network route-table route create --resource-group udr-test --name route109 --route-table-name RT --address-prefix 10.1.109.0/24 --next-hop-type VirtualAppliance --next-hop-ip-address 10.20.0.4
az network route-table route create --resource-group udr-test --name route110 --route-table-name RT --address-prefix 10.1.110.0/24 --next-hop-type VirtualAppliance --next-hop-ip-address 10.20.0.4
az network route-table route create --resource-group udr-test --name route111 --route-table-name RT --address-prefix 10.1.111.0/24 --next-hop-type VirtualAppliance --next-hop-ip-address 10.20.0.4
az network route-table route create --resource-group udr-test --name route112 --route-table-name RT --address-prefix 10.1.112.0/24 --next-hop-type VirtualAppliance --next-hop-ip-address 10.20.0.4
az network route-table route create --resource-group udr-test --name route113 --route-table-name RT --address-prefix 10.1.113.0/24 --next-hop-type VirtualAppliance --next-hop-ip-address 10.20.0.4
az network route-table route create --resource-group udr-test --name route114 --route-table-name RT --address-prefix 10.1.114.0/24 --next-hop-type VirtualAppliance --next-hop-ip-address 10.20.0.4
az network route-table route create --resource-group udr-test --name route115 --route-table-name RT --address-prefix 10.1.115.0/24 --next-hop-type VirtualAppliance --next-hop-ip-address 10.20.0.4
az network route-table route create --resource-group udr-test --name route116 --route-table-name RT --address-prefix 10.1.116.0/24 --next-hop-type VirtualAppliance --next-hop-ip-address 10.20.0.4
az network route-table route create --resource-group udr-test --name route117 --route-table-name RT --address-prefix 10.1.117.0/24 --next-hop-type VirtualAppliance --next-hop-ip-address 10.20.0.4
az network route-table route create --resource-group udr-test --name route118 --route-table-name RT --address-prefix 10.1.118.0/24 --next-hop-type VirtualAppliance --next-hop-ip-address 10.20.0.4
az network route-table route create --resource-group udr-test --name route119 --route-table-name RT --address-prefix 10.1.119.0/24 --next-hop-type VirtualAppliance --next-hop-ip-address 10.20.0.4
az network route-table route create --resource-group udr-test --name route120 --route-table-name RT --address-prefix 10.1.120.0/24 --next-hop-type VirtualAppliance --next-hop-ip-address 10.20.0.4
az network route-table route create --resource-group udr-test --name route121 --route-table-name RT --address-prefix 10.1.121.0/24 --next-hop-type VirtualAppliance --next-hop-ip-address 10.20.0.4
az network route-table route create --resource-group udr-test --name route122 --route-table-name RT --address-prefix 10.1.122.0/24 --next-hop-type VirtualAppliance --next-hop-ip-address 10.20.0.4
az network route-table route create --resource-group udr-test --name route123 --route-table-name RT --address-prefix 10.1.123.0/24 --next-hop-type VirtualAppliance --next-hop-ip-address 10.20.0.4
az network route-table route create --resource-group udr-test --name route124 --route-table-name RT --address-prefix 10.1.124.0/24 --next-hop-type VirtualAppliance --next-hop-ip-address 10.20.0.4
az network route-table route create --resource-group udr-test --name route125 --route-table-name RT --address-prefix 10.1.125.0/24 --next-hop-type VirtualAppliance --next-hop-ip-address 10.20.0.4
az network route-table route create --resource-group udr-test --name route126 --route-table-name RT --address-prefix 10.1.126.0/24 --next-hop-type VirtualAppliance --next-hop-ip-address 10.20.0.4
az network route-table route create --resource-group udr-test --name route127 --route-table-name RT --address-prefix 10.1.127.0/24 --next-hop-type VirtualAppliance --next-hop-ip-address 10.20.0.4
az network route-table route create --resource-group udr-test --name route128 --route-table-name RT --address-prefix 10.1.128.0/24 --next-hop-type VirtualAppliance --next-hop-ip-address 10.20.0.4
az network route-table route create --resource-group udr-test --name route129 --route-table-name RT --address-prefix 10.1.129.0/24 --next-hop-type VirtualAppliance --next-hop-ip-address 10.20.0.4
az network route-table route create --resource-group udr-test --name route130 --route-table-name RT --address-prefix 10.1.130.0/24 --next-hop-type VirtualAppliance --next-hop-ip-address 10.20.0.4
az network route-table route create --resource-group udr-test --name route131 --route-table-name RT --address-prefix 10.1.131.0/24 --next-hop-type VirtualAppliance --next-hop-ip-address 10.20.0.4
az network route-table route create --resource-group udr-test --name route132 --route-table-name RT --address-prefix 10.1.132.0/24 --next-hop-type VirtualAppliance --next-hop-ip-address 10.20.0.4
az network route-table route create --resource-group udr-test --name route133 --route-table-name RT --address-prefix 10.1.133.0/24 --next-hop-type VirtualAppliance --next-hop-ip-address 10.20.0.4
az network route-table route create --resource-group udr-test --name route134 --route-table-name RT --address-prefix 10.1.134.0/24 --next-hop-type VirtualAppliance --next-hop-ip-address 10.20.0.4
az network route-table route create --resource-group udr-test --name route135 --route-table-name RT --address-prefix 10.1.135.0/24 --next-hop-type VirtualAppliance --next-hop-ip-address 10.20.0.4
az network route-table route create --resource-group udr-test --name route136 --route-table-name RT --address-prefix 10.1.136.0/24 --next-hop-type VirtualAppliance --next-hop-ip-address 10.20.0.4
az network route-table route create --resource-group udr-test --name route137 --route-table-name RT --address-prefix 10.1.137.0/24 --next-hop-type VirtualAppliance --next-hop-ip-address 10.20.0.4
az network route-table route create --resource-group udr-test --name route138 --route-table-name RT --address-prefix 10.1.138.0/24 --next-hop-type VirtualAppliance --next-hop-ip-address 10.20.0.4
az network route-table route create --resource-group udr-test --name route139 --route-table-name RT --address-prefix 10.1.139.0/24 --next-hop-type VirtualAppliance --next-hop-ip-address 10.20.0.4
az network route-table route create --resource-group udr-test --name route140 --route-table-name RT --address-prefix 10.1.140.0/24 --next-hop-type VirtualAppliance --next-hop-ip-address 10.20.0.4
az network route-table route create --resource-group udr-test --name route141 --route-table-name RT --address-prefix 10.1.141.0/24 --next-hop-type VirtualAppliance --next-hop-ip-address 10.20.0.4
az network route-table route create --resource-group udr-test --name route142 --route-table-name RT --address-prefix 10.1.142.0/24 --next-hop-type VirtualAppliance --next-hop-ip-address 10.20.0.4
az network route-table route create --resource-group udr-test --name route143 --route-table-name RT --address-prefix 10.1.143.0/24 --next-hop-type VirtualAppliance --next-hop-ip-address 10.20.0.4
az network route-table route create --resource-group udr-test --name route144 --route-table-name RT --address-prefix 10.1.144.0/24 --next-hop-type VirtualAppliance --next-hop-ip-address 10.20.0.4
az network route-table route create --resource-group udr-test --name route145 --route-table-name RT --address-prefix 10.1.145.0/24 --next-hop-type VirtualAppliance --next-hop-ip-address 10.20.0.4
az network route-table route create --resource-group udr-test --name route146 --route-table-name RT --address-prefix 10.1.146.0/24 --next-hop-type VirtualAppliance --next-hop-ip-address 10.20.0.4
az network route-table route create --resource-group udr-test --name route147 --route-table-name RT --address-prefix 10.1.147.0/24 --next-hop-type VirtualAppliance --next-hop-ip-address 10.20.0.4
az network route-table route create --resource-group udr-test --name route148 --route-table-name RT --address-prefix 10.1.148.0/24 --next-hop-type VirtualAppliance --next-hop-ip-address 10.20.0.4
az network route-table route create --resource-group udr-test --name route149 --route-table-name RT --address-prefix 10.1.149.0/24 --next-hop-type VirtualAppliance --next-hop-ip-address 10.20.0.4
az network vnet subnet update --name test --resource-group udr-test --vnet-name VNET --address-prefixes 10.10.0.0/26 --route-table RT
